Pull Request: Adding Functionality to To-Do List
Zafron047/ToDoList pull request #2
Opened 2023-06-09 21:39 UTC by Zafron047

This pull request adds new functionality to the existing To-Do List project implemented in JavaScript with HTML and CSS. The following features have been implemented:

- [x]  Addition of new tasks: A new function has been implemented to add a new task to the list. This function adds a new element to the array, with the property 'completed' set to false by default and the 'index' property set to the value of the new array length. This ensures that the newly added task is appended to the end of the list and has a unique index.
- [x] Deletion of tasks: Another function has been implemented to delete a task from the list. When a task is deleted, the indexes of the remaining tasks are updated to represent the current list order. For example, if the first task with index 1 is deleted, the index of the next task will be updated to 1.
- [x] Editing task descriptions: The functionality to edit task descriptions has been implemented, allowing users to modify the descriptions of existing tasks.
- [x] Local storage integration: All changes made to the To-Do List, including task addition, deletion, and description editing, are now saved in local storage. This ensures that the changes persist even if the page is refreshed or closed.

Kindly review and offer the opportunity to merge this pull request to incorporate the new features and enhance the functionality of the To-Do List project.

Best Regards,
Zafron. 😺

2023-06-09 22:01 UTC, roshan-bajgain requested changes
Hi @Zafron047, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Add is working fine ✔️ 
- Edit and delete is working fine ✔️ 

## Required Changes ♻️
- [ ] Also I would suggest you please fix the branch conflict then you are good to go.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 22:01 UTC, roshan-bajgain commented on src/index.js
> +
- [ ] According to the project requirement you should create a new Javascript file for new functionality. So this webpack helps to create a module so the code will be easier to read and also to find debug. Please I would suggest creating a new Javascript file for new functionality rather than that everything working fine like adding, editing, deleting etc.
### Requirement
![his](https://github.com/Zafron047/ToDoList/assets/81727988/8e87eee9-8820-455d-a2b8-9ef79ba54fd3)

2023-06-10 03:07 UTC, Zafron047 commented on src/index.js
> +
Okay, thanks for the advice.

- [x] I have worked on it. I have created a separate file under module that holds the functions dependent on the for each loop.

- And I have also created a separate file under module that could be separated to function independently.

2023-06-10 03:19 UTC, BenMukebo approved these changes
### Hi @Zafron047, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- A function for adding a new task  is implemented. ✔️  
- A function for editing task descriptions is implemented. ✔️  
- A function for deleting a task. ✔️  
- Deleting a task update all remaining items' indexes,  ✔️  
- All changes to the To-Do List are saved in local storage :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 09:28 UTC, Zafron047 commented
@BenMukebo Thanks a lot for the review.

2023-06-10 11:15 UTC, merged